depoly prometus and grafana

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -43,4 +43,38 @@ jobs:
 
       - name: Execute script on EC2
         run: |
-          ssh ec2 "cd $REPO_NAME && bash deploy-monitoring.sh ~/${REPO_NAME}"
+         
+
+          # SSH into EC2 and run install + deploy
+          ssh ec2 "
+            sudo dpkg --configure -a
+            sudo apt-get update
+
+            if ! command -v docker &> /dev/null; then
+              echo 'Installing Docker...'
+              sudo apt-get update
+              sudo apt-get install -y ca-certificates curl
+              sudo install -m 0755 -d /etc/apt/keyrings
+              sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
+              sudo chmod a+r /etc/apt/keyrings/docker.asc
+
+              arch=\$(dpkg --print-architecture)
+              codename=\$(. /etc/os-release && echo \${UBUNTU_CODENAME:-\$VERSION_CODENAME})
+              echo \"deb [arch=\$arch signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \$codename stable\" | \
+                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+
+              sudo apt-get update
+              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+            else
+              echo 'Docker already installed.'
+            fi
+
+            if ! command -v docker &> /dev/null; then
+              echo 'Docker installation failed or not found. Exiting.'
+              exit 1
+            fi
+
+            echo 'Starting Docker Compose services...'
+            sudo docker compose -f docker-compose.monitoring.yaml pull
+            sudo docker compose -f docker-compose.monitoring.yaml up -d
+          "
